version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "7004:80"
    depends_on:
      - backend

  hr:
    build:
      context: ./HR
    ports:
      - "7005:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "3098:3098"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin234
      - POSTGRES_DB=Leave
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: Leave
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres_data:

